apiVersion: apps/v1
kind: Deployment
metadata:
  name: social-api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: social-api
  template:
    metadata:
      labels:
        app: social-api
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox
          command: ['sh', '-c', 'until nc -z social-postgres 5432; do echo waiting for postgres; sleep 2; done']
      containers:
        - name: social-api
          image: ghcr.io/1000bang/social:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://social-postgres:5432/mysocial"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: social-api-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: social-api-secret
                  key: DB_PASSWORD
            - name: TOKEN_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: social-api-secret
                  key: TOKEN_ENCRYPTION_KEY
            - name: WEBHOOK_VERIFY_TOKEN
              valueFrom:
                secretKeyRef:
                  name: social-api-secret
                  key: WEBHOOK_VERIFY_TOKEN
            - name: WEBHOOK_APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: social-api-secret
                  key: WEBHOOK_APP_SECRET
            - name: META_APP_ID
              valueFrom:
                secretKeyRef:
                  name: social-api-secret
                  key: META_APP_ID
            - name: META_APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: social-api-secret
                  key: META_APP_SECRET
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: social-api-secret
                  key: JWT_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: social-api-svc
  namespace: default
spec:
  selector:
    app: social-api
  ports:
    - port: 80
      targetPort: 8080
  type: NodePort
